name: alerts
'on':
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      #YAML_FILE_PATH: normative-analytics-dbt/slack_alerts.yml
      #SLACK_WEBHOOK_URL: '= ${{ secrets.SLACK_WEBHOOK_URL }}'
      DBT_SERVICE_ACCOUNT_TOKEN: '= ${{ secrets.DBT_SERVICE_ACCOUNT_TOKEN }}'
    steps:
      - uses: actions/checkout@v3
        with:
          repository: adhikarisidd17/Bigquery_DW
      - name: "Copy yaml file"
        run: "cp slack_alerts.yml slack_alerts_config.yml"
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml
          pip install google-cloud-bigquery
      - uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.DBT_SERVICE_ACCOUNT_TOKEN }}' 
      - name: Execute python script
        run: python python/run_alerts.py
